/* ITNEROL — Seed de Dados
 * Backup embarcado inline para inicialização imediata do sistema.
 * Em produção, o usuário deve usar "Relatórios → Importar Backup JSON"
 * para carregar o arquivo ITNEROL_Backup_Completo_2026-07-22.json.
 * Estrutura idêntica ao backup original — mesmos campos, mesmas tabelas.
 */
window.BACKUP_DATA = {
  v: "7.4",
  s: "ITNEROL Sistema Comercial",
  b: "2026-07-22T14:28:35.667Z",
  usuarios: [
    {nome:"Administrador",     email:"admin@itnerol.com.br",   senha_hash:"itnerol2025",  perfil:"admin"},
    {nome:"Comercial ITNEROL", email:"comercial@itnerol.com.br",senha_hash:"comercial123",perfil:"comercial"},
    {nome:"OPERACIONAL",       email:"CCO@ITNEROL.COM.BR",     senha_hash:"CCO2026",      perfil:"operacional"},
    {nome:"Visualizador",      email:"view@itnerol.com.br",    senha_hash:"view123",      perfil:"visualizador"}
  ],
  clientes: [
    {razao_social:"BUSUP OPERAÇÕES",       nome_fantasia:"BUSUP",            cnpj:"",               segmento:"TRANSPORTES", contato_nome:"THIAGO / JACSON", contato_cargo:"GESTORES OPERACIONAIS", contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"SÃO PAULO",       status:"Ativo", data_inicio:"2024-01-02"},
    {razao_social:"FLAMBOIA ALIMENTOS",    nome_fantasia:"FLAMBOIA ALIMENTOS",cnpj:"61252540000157", segmento:"ALIMENTOS",    contato_nome:"OSEAS",         contato_cargo:"GESTOR RH",         contato_email:"oseas@flamboia.com.br", contato_telefone:"11999956850", endereco:"AVENIDA ANTONIO ORTEGA 3604",     cidade:"CABREUVA",       status:"Ativo", data_inicio:"2015-09-14"},
    {razao_social:"PRIETO ALIMENTOS LTDA", nome_fantasia:"PRIETO ALIMENTOS", cnpj:"61.752.739/0001-44", segmento:"ALIMENTICIA", contato_nome:"QUEITIANE",    contato_cargo:"COORDENADORA RH",   contato_email:"queitiane.farias@prietoalimentos.com.br", contato_telefone:"1199614-1074", endereco:"Avenida Vereador Joaquim Pereira Barbosa , 777", cidade:"CAJAMAR", status:"Ativo", data_inicio:"2025-04-30"},
    {razao_social:"URBITEC CONSTRUÇÕES LTDA", nome_fantasia:"URBITEC CONSTRUÇÕES", cnpj:"",         segmento:"CONSTRUÇÃO",  contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"JUNDIAI",        status:"Ativo", data_inicio:""},
    {razao_social:"PLANET - TOP BRANDS",   nome_fantasia:"PLANET",            cnpj:"",               segmento:"",             contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"JUNDIAÍ",        status:"Ativo", data_inicio:""},
    {razao_social:"MILLENIUM COBRANÇAS",   nome_fantasia:"MILLENIUM COBRANÇAS EMPRESARIAIS", cnpj:"",      segmento:"",             contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"VÁRZEA PAULISTA",status:"Ativo", data_inicio:""},
    {razao_social:"JAPI EMBALAGENS LTDA",  nome_fantasia:"JAPI EMBALAGENS",  cnpj:"",               segmento:"EMBALAGENS",   contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"JUNDIAI",        status:"Ativo", data_inicio:""},
    {razao_social:"TUBAL EQUIPAMENTOS",    nome_fantasia:"TUBAL",             cnpj:"",               segmento:"INDÚSTRIA",    contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"VARZEA PAULISTA",status:"Ativo", data_inicio:""},
    {razao_social:"FL BRASIL HOLDING",     nome_fantasia:"TRAGETTA",          cnpj:"",               segmento:"LOGÍSTICA",    contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"JUNDIAI",        status:"Ativo", data_inicio:""},
    {razao_social:"DINIZ COMERCIO ATACADISTA", nome_fantasia:"DINIZ FOODS",  cnpj:"",               segmento:"ALIMENTOS",    contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"LOUVEIRA",       status:"Ativo", data_inicio:""},
    {razao_social:"MITUTOYO SUL AMERICANA", nome_fantasia:"MITUTOYO",          cnpj:"",               segmento:"METROLOGIA",   contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"JUNDIAI",        status:"Ativo", data_inicio:""},
    {razao_social:"BALDI INDUSTRIA E COMERCIO", nome_fantasia:"BALDI",       cnpj:"",               segmento:"INDÚSTRIA",    contato_nome:"",            contato_cargo:"",                  contato_email:"",                 contato_telefone:"",      endereco:"",                              cidade:"VÁRZEA PAULISTA",status:"Ativo", data_inicio:""}
  ],
  veiculos: [
    {placa:"CUB1I69", numero_frota:"1087", tipo:"Ônibus",   modelo:"MPOLO IDEALE R",                ano:"2009", capacidade:"48", status:"Disponível"},
    {placa:"DMR7G00", numero_frota:"1597", tipo:"Van",      modelo:"MERCEDES SPRINTER 415 CDI",     ano:"2018", capacidade:"16", status:"Disponível", observacoes:"COR: BRANCA | ANO MOD: 2019"},
    {placa:"SJV1J12", numero_frota:"1587", tipo:"Van",      modelo:"FORD TRANSIT 410 B",            ano:"2023", capacidade:"15", status:"Disponível"},
    {placa:"ABC1D23", numero_frota:"1100", tipo:"Ônibus",   modelo:"VOLKSBUS 17.230 OD",            ano:"2019", capacidade:"46", status:"Em Uso"},
    {placa:"BCD2E34", numero_frota:"1110", tipo:"Microônibus", modelo:"IVECO CITYCLASS 70C17",       ano:"2021", capacidade:"30", status:"Disponível"},
    {placa:"CDE3F45", numero_frota:"1200", tipo:"Van",      modelo:"RENAULT MASTER",                ano:"2020", capacidade:"16", status:"Manutenção"},
    {placa:"EFG4H56", numero_frota:"1300", tipo:"Sedan Executivo", modelo:"TOYOTA COROLLA ALTIS",     ano:"2022", capacidade:"4",  status:"Em Uso"},
    {placa:"GHI5J67", numero_frota:"1301", tipo:"Sedan Executivo", modelo:"TOYOTA COROLLA XEI",       ano:"2023", capacidade:"4",  status:"Disponível"},
    {placa:"JKL6K78", numero_frota:"1400", tipo:"SUV",      modelo:"JEEP COMPASS LIMITED",          ano:"2023", capacidade:"5",  status:"Disponível"},
    {placa:"MNO7L89", numero_frota:"1410", tipo:"Van",      modelo:"MERCEDES SPRINTER 417",         ano:"2024", capacidade:"17", status:"Disponível"}
  ],
  motoristas: [
    {nome:"ALUIZIO CABRAL DA SILVA",     cpf:"", cnh:"", categoria_cnh:"D", vencimento_cnh:"2027-08-15", telefone:"",     salario_base:"3200", status:"Ativo",     endereco:"", cidade_motorista:"JUNDIAI",  categoria_veiculo:"Ônibus"},
    {nome:"CARLOS EDUARDO PEREIRA",      cpf:"", cnh:"", categoria_cnh:"D", vencimento_cnh:"2026-09-22", telefone:"",     salario_base:"3500", status:"Ativo",     endereco:"", cidade_motorista:"JUNDIAI",  categoria_veiculo:"Ônibus"},
    {nome:"EVERTON RODRIGUES MESSIAS",   cpf:"", cnh:"", categoria_cnh:"D", vencimento_cnh:"2027-03-10", telefone:"",     salario_base:"3300", status:"Ativo",     endereco:"", cidade_motorista:"VÁRZEA PAULISTA", categoria_veiculo:"Ônibus"},
    {nome:"FERNANDO APARECIDO SANTOS",   cpf:"", cnh:"", categoria_cnh:"D", vencimento_cnh:"2026-08-30", telefone:"",     salario_base:"3400", status:"Ativo",     endereco:"", cidade_motorista:"JUNDIAI",  categoria_veiculo:"Microônibus"},
    {nome:"JOSÉ ROBERTO DA SILVA",       cpf:"", cnh:"", categoria_cnh:"E", vencimento_cnh:"2026-12-05", telefone:"",     salario_base:"3600", status:"Férias",    endereco:"", cidade_motorista:"CAJAMAR",  categoria_veiculo:"Ônibus"},
    {nome:"MARCOS ANTÔNIO OLIVEIRA",     cpf:"", cnh:"", categoria_cnh:"D", vencimento_cnh:"2027-06-18", telefone:"",     salario_base:"3200", status:"Ativo",     endereco:"", cidade_motorista:"CABREUVA",categoria_veiculo:"Van"},
    {nome:"PAULO HENRIQUE SOUZA",        cpf:"", cnh:"", categoria_cnh:"B", vencimento_cnh:"2027-11-12", telefone:"",     salario_base:"2800", status:"Ativo",     endereco:"", cidade_motorista:"JUNDIAI",  categoria_veiculo:"Sedan Executivo"},
    {nome:"RICARDO ALEXANDRE LIMA",      cpf:"", cnh:"", categoria_cnh:"D", vencimento_cnh:"2026-10-25", telefone:"",     salario_base:"3300", status:"Ativo",     endereco:"", cidade_motorista:"JUNDIAI",  categoria_veiculo:"Van"}
  ],
  contratos: [
    {numero_contrato:"", cliente_id:"cli-001", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"28954.75", km_mensal_contratada:"1178.25", data_inicio:"2024-01-02", data_fim:"",               onibus_qtd:"2", micro_qtd:"0", van_qtd:"0", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-002", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"23650.00", km_mensal_contratada:"2640",    data_inicio:"2024-03-15", data_fim:"2026-12-31",      onibus_qtd:"0", micro_qtd:"1", van_qtd:"2", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-003", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"58280.00", km_mensal_contratada:"6120",    data_inicio:"2025-04-30", data_fim:"2026-12-02",      onibus_qtd:"0", micro_qtd:"0", van_qtd:"4", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-004", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"43800.00", km_mensal_contratada:"5315.20", data_inicio:"2025-12-01", data_fim:"2026-12-01",      onibus_qtd:"0", micro_qtd:"1", van_qtd:"1", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-005", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"74700.00", km_mensal_contratada:"9455",    data_inicio:"2025-11-01", data_fim:"2026-11-01",      onibus_qtd:"0", micro_qtd:"0", van_qtd:"3", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-011", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"155432.00", km_mensal_contratada:"14523", data_inicio:"2020-03-02", data_fim:"2026-12-02",      onibus_qtd:"6", micro_qtd:"0", van_qtd:"0", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-006", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"32450.00", km_mensal_contratada:"3400",    data_inicio:"2025-06-10", data_fim:"2026-06-10",      onibus_qtd:"0", micro_qtd:"0", van_qtd:"2", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-007", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"18900.00", km_mensal_contratada:"1800",    data_inicio:"2025-08-01", data_fim:"2026-08-01",      onibus_qtd:"0", micro_qtd:"0", van_qtd:"1", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-008", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"41200.00", km_mensal_contratada:"4200",    data_inicio:"2024-09-15", data_fim:"2026-09-15",      onibus_qtd:"1", micro_qtd:"0", van_qtd:"1", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-009", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"67300.00", km_mensal_contratada:"7100",    data_inicio:"2025-02-20", data_fim:"2027-02-20",      onibus_qtd:"2", micro_qtd:"0", van_qtd:"2", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-010", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"98700.00", km_mensal_contratada:"10200",   data_inicio:"2024-11-05", data_fim:"2026-11-05",      onibus_qtd:"3", micro_qtd:"0", van_qtd:"2", passeio_qtd:"0"},
    {numero_contrato:"", cliente_id:"cli-012", tipo_servico:"Fretamento Corporativo", status:"Ativo", valor_mensal:"22500.00", km_mensal_contratada:"2300",    data_inicio:"2025-10-01", data_fim:"2026-10-01",      onibus_qtd:"0", micro_qtd:"1", van_qtd:"0", passeio_qtd:"0"}
  ],
  linhas: [
    {codigo_linha:"01127", cliente_id:"cli-001", descricao:"BUSUP 9058 - Azul Jundiaí - BN/FN 1127 E", itinerario:"Jundiaí → Valinhos",            endereco_garagem:"TEREZA VECHIATTI TRIGO, 120 — COUNTRY CLUB, VALINHOS / SP", endereco_inicio_linha:"Terminal Eloy Chaves - Parque Eloy Chaves, Jundiaí - SP",        km_ocioso_ida:"12",   km_ocioso_volta:"12",   km_ocioso_total:"24",   tipo_veiculo:"Ônibus",    veiculo_id:"vei-001", motorista_id:"mot-001", km_diaria:"58",   dias_mes:"22",  km_mensal_contratada:"1276", horario_ida:"06:00", horario_volta:"18:00", status:"Ativa"},
    {codigo_linha:"01128", cliente_id:"cli-001", descricao:"BUSUP 9059 - Verde Jundiaí",               itinerario:"Jundiaí → Vinhedo",            endereco_garagem:"TEREZA VECHIATTI TRIGO, 120",                                endereco_inicio_linha:"Terminal Eloy Chaves",                                          km_ocioso_ida:"14",   km_ocioso_volta:"14",   km_ocioso_total:"28",   tipo_veiculo:"Ônibus",    veiculo_id:"",       motorista_id:"mot-002", km_diaria:"62",   dias_mes:"22",  km_mensal_contratada:"1364", horario_ida:"06:30", horario_volta:"18:30", status:"Ativa"},
    {codigo_linha:"02101", cliente_id:"cli-002", descricao:"FLAMBOIA - Turno Manhã",                  itinerario:"Cabreúva → Jundiaí",            endereco_garagem:"Garagem Cabreúva",                                          endereco_inicio_linha:"Cabreúva Centro",                                              km_ocioso_ida:"8",    km_ocioso_volta:"8",    km_ocioso_total:"16",   tipo_veiculo:"Van",       veiculo_id:"vei-002", motorista_id:"mot-003", km_diaria:"60",   dias_mes:"22",  km_mensal_contratada:"1320", horario_ida:"05:45", horario_volta:"17:00", status:"Ativa"},
    {codigo_linha:"02102", cliente_id:"cli-002", descricao:"FLAMBOIA - Turno Tarde",                  itinerario:"Jundiaí → Cabreúva",            endereco_garagem:"Garagem Cabreúva",                                          endereco_inicio_linha:"Jundiaí",                                                       km_ocioso_ida:"8",    km_ocioso_volta:"8",    km_ocioso_total:"16",   tipo_veiculo:"Van",       veiculo_id:"vei-003", motorista_id:"mot-004", km_diaria:"60",   dias_mes:"22",  km_mensal_contratada:"1320", horario_ida:"14:00", horario_volta:"02:00", status:"Ativa"},
    {codigo_linha:"03101", cliente_id:"cli-003", descricao:"PRIETO - Cajamar Linha 1",                itinerario:"Cajamar → Jundiaí",             endereco_garagem:"Garagem Cajamar",                                           endereco_inicio_linha:"Cajamar",                                                        km_ocioso_ida:"22",   km_ocioso_volta:"22",   km_ocioso_total:"44",   tipo_veiculo:"Van",       veiculo_id:"",       motorista_id:"mot-005", km_diaria:"73",   dias_mes:"22",  km_mensal_contratada:"1606", horario_ida:"06:00", horario_volta:"18:00", status:"Ativa"},
    {codigo_linha:"03102", cliente_id:"cli-003", descricao:"PRIETO - Cajamar Linha 2",                itinerario:"Cajamar → Franco da Rocha",     endereco_garagem:"Garagem Cajamar",                                           endereco_inicio_linha:"Cajamar",                                                        km_ocioso_ida:"30",   km_ocioso_volta:"30",   km_ocioso_total:"60",   tipo_veiculo:"Van",       veiculo_id:"",       motorista_id:"mot-006", km_diaria:"80",   dias_mes:"22",  km_mensal_contratada:"1760", horario_ida:"05:30", horario_volta:"17:30", status:"Ativa"},
    {codigo_linha:"03103", cliente_id:"cli-003", descricao:"PRIETO - Cajamar Linha 3",                itinerario:"Cajamar → São Paulo",           endereco_garagem:"Garagem Cajamar",                                           endereco_inicio_linha:"Cajamar",                                                        km_ocioso_ida:"35",   km_ocioso_volta:"35",   km_ocioso_total:"70",   tipo_veiculo:"Van",       veiculo_id:"",       motorista_id:"mot-007", km_diaria:"125",  dias_mes:"22",  km_mensal_contratada:"2750", horario_ida:"05:00", horario_volta:"17:00", status:"Ativa"},
    {codigo_linha:"11101", cliente_id:"cli-011", descricao:"MITUTOYO - Linha 01 Norte",               itinerario:"Jundiaí Norte",                endereco_garagem:"MITUTOYO - Av. Honda",                                       endereco_inicio_linha:"MITUTOYO Sede",                                                  km_ocioso_ida:"15",   km_ocioso_volta:"15",   km_ocioso_total:"30",   tipo_veiculo:"Ônibus",    veiculo_id:"",       motorista_id:"",       km_diaria:"65",   dias_mes:"22",  km_mensal_contratada:"1430", horario_ida:"06:15", horario_volta:"18:15", status:"Ativa"},
    {codigo_linha:"11102", cliente_id:"cli-011", descricao:"MITUTOYO - Linha 02 Sul",                 itinerario:"Jundiaí Sul",                  endereco_garagem:"MITUTOYO - Av. Honda",                                       endereco_inicio_linha:"MITUTOYO Sede",                                                  km_ocioso_ida:"20",   km_ocioso_volta:"20",   km_ocioso_total:"40",   tipo_veiculo:"Ônibus",    veiculo_id:"",       motorista_id:"",       km_diaria:"78",   dias_mes:"22",  km_mensal_contratada:"1716", horario_ida:"06:00", horario_volta:"18:00", status:"Ativa"},
    {codigo_linha:"11103", cliente_id:"cli-011", descricao:"MITUTOYO - Linha 03 Leste",               itinerario:"Jundiaí Leste",                endereco_garagem:"MITUTOYO - Av. Honda",                                       endereco_inicio_linha:"MITUTOYO Sede",                                                  km_ocioso_ida:"18",   km_ocioso_volta:"18",   km_ocioso_total:"36",   tipo_veiculo:"Ônibus",    veiculo_id:"",       motorista_id:"",       km_diaria:"72",   dias_mes:"22",  km_mensal_contratada:"1584", horario_ida:"06:30", horario_volta:"18:30", status:"Ativa"}
  ],
  apuracao: [
    {mes_ano:"06/2026", cliente_id:"cli-005", km_contratada:"9455",  km_rodada:"9455",  faturamento_contrato:"74700.00", faturamento_realizado:"74700.00", viagens_extras:"0",  custo_motoristas:"45330.00", pedagio:"1850.00", impostos:"7860.00", depreciacao_veiculo:"6660.00", outras_despesas:"660.00",  custo_total:"86659.35",  margem_bruta:"-11959.35", margem_percentual:-16.01},
    {mes_ano:"05/2026", cliente_id:"cli-005", km_contratada:"9455",  km_rodada:"9200",  faturamento_contrato:"74700.00", faturamento_realizado:"74700.00", viagens_extras:"1500",custo_motoristas:"45330.00", pedagio:"1780.00", impostos:"7860.00", depreciacao_veiculo:"6660.00", outras_despesas:"720.00",  custo_total:"85600.00", margem_bruta:"-10900.00",margem_percentual:-14.59},
    {mes_ano:"06/2026", cliente_id:"cli-003", km_contratada:"6120",  km_rodada:"6020",  faturamento_contrato:"58280.00", faturamento_realizado:"58280.00", viagens_extras:"0",  custo_motoristas:"32400.00", pedagio:"1200.00", impostos:"6120.00", depreciacao_veiculo:"4800.00", outras_despesas:"540.00",  custo_total:"54880.00", margem_bruta:"3400.00",   margem_percentual:5.83 },
    {mes_ano:"05/2026", cliente_id:"cli-003", km_contratada:"6120",  km_rodada:"6500",  faturamento_contrato:"58280.00", faturamento_realizado:"58280.00", viagens_extras:"2000",custo_motoristas:"32400.00", pedagio:"1340.00", impostos:"6120.00", depreciacao_veiculo:"4800.00", outras_despesas:"480.00",  custo_total:"54560.00", margem_bruta:"3720.00",   margem_percentual:6.38 },
    {mes_ano:"06/2026", cliente_id:"cli-002", km_contratada:"2640",  km_rodada:"2640",  faturamento_contrato:"23650.00", faturamento_realizado:"23650.00", viagens_extras:"0",   custo_motoristas:"14800.00", pedagio:"480.00",  impostos:"2483.00", depreciacao_veiculo:"2200.00", outras_despesas:"220.00",  custo_total:"22700.00", margem_bruta:"950.00",    margem_percentual:4.02 },
    {mes_ano:"06/2026", cliente_id:"cli-011", km_contratada:"14523", km_rodada:"14523",faturamento_contrato:"155432.00",faturamento_realizado:"155432.00",viagens_extras:"0",custo_motoristas:"98800.00", pedagio:"3200.00",impostos:"16320.00",depreciacao_veiculo:"13200.00",outras_despesas:"1800.00",custo_total:"156340.00",margem_bruta:"-908.00",    margem_percentual:-0.58 },
    {mes_ano:"06/2026", cliente_id:"cli-001", km_contratada:"1178",  km_rodada:"1178",  faturamento_contrato:"28954.75", faturamento_realizado:"28954.75", viagens_extras:"0",   custo_motoristas:"18600.00", pedagio:"320.00",  impostos:"3040.00", depreciacao_veiculo:"2600.00", outras_despesas:"180.00",  custo_total:"25860.00", margem_bruta:"3094.75",   margem_percentual:10.69},
    {mes_ano:"05/2026", cliente_id:"cli-001", km_contratada:"1178",  km_rodada:"1178",  faturamento_contrato:"28954.75", faturamento_realizado:"28954.75", viagens_extras:"0",   custo_motoristas:"18600.00", pedagio:"340.00",  impostos:"3040.00", depreciacao_veiculo:"2600.00", outras_despesas:"200.00",  custo_total:"25880.00", margem_bruta:"3074.75",   margem_percentual:10.62},
    {mes_ano:"06/2026", cliente_id:"cli-004", km_contratada:"5315",  km_rodada:"5315",  faturamento_contrato:"43800.00", faturamento_realizado:"43800.00", viagens_extras:"0",   custo_motoristas:"25200.00", pedagio:"950.00",  impostos:"4599.00", depreciacao_veiculo:"3900.00", outras_despesas:"420.00",  custo_total:"39680.00", margem_bruta:"4120.00",   margem_percentual:9.41 },
    {mes_ano:"06/2026", cliente_id:"cli-006", km_contratada:"3400",  km_rodada:"3400",  faturamento_contrato:"32450.00", faturamento_realizado:"32450.00", viagens_extras:"0",   custo_motoristas:"19400.00", pedagio:"620.00",  impostos:"3408.00", depreciacao_veiculo:"2890.00", outras_despesas:"290.00",  custo_total:"30120.00", margem_bruta:"2330.00",   margem_percentual:7.18 },
    {mes_ano:"06/2026", cliente_id:"cli-007", km_contratada:"1800",  km_rodada:"1800",  faturamento_contrato:"18900.00", faturamento_realizado:"18900.00", viagens_extras:"0",   custo_motoristas:"10800.00", pedagio:"280.00",  impostos:"1985.00", depreciacao_veiculo:"1500.00", outras_despesas:"180.00",  custo_total:"16520.00", margem_bruta:"2380.00",   margem_percentual:12.59},
    {mes_ano:"06/2026", cliente_id:"cli-008", km_contratada:"4200",  km_rodada:"4200",  faturamento_contrato:"41200.00", faturamento_realizado:"41200.00", viagens_extras:"0",   custo_motoristas:"23200.00", pedagio:"780.00",  impostos:"4326.00", depreciacao_veiculo:"3760.00", outras_despesas:"360.00",  costo_total_alt:"",         custo_total:"36080.00", margem_bruta:"5120.00",   margem_percentual:12.43},
    {mes_ano:"06/2026", cliente_id:"cli-009", km_contratada:"7100",  km_rodada:"7100",  faturamento_contrato:"67300.00", faturamento_realizado:"67300.00", viagens_extras:"0",   custo_motoristas:"39600.00", pedagio:"1380.00", impostos:"7067.00", depreciacao_veiculo:"6300.00", outras_despesas:"520.00",  custo_total:"60140.00", margem_bruta:"7160.00",   margem_percentual:10.64},
    {mes_ano:"06/2026", cliente_id:"cli-010", km_contratada:"10200", km_rodada:"10200",faturamento_contrato:"98700.00", faturamento_realizado:"98700.00", viagens_extras:"0",   custo_motoristas:"58200.00", pedagio:"2100.00",impostos:"10364.00",depreciacao_veiculo:"8800.00", outras_despesas:"780.00", custo_total:"88120.00", margem_bruta:"10580.00",  margem_percentual:10.72}
  ],
  reclamacoes: [
    {data:"2026-06-25", cliente_id:"cli-002", tipo:"Conduta do Motorista",  status:"Resolvida",  descricao:"EMPRESA RECLAMOU QUE O MOTORISTA ESTAVA COM EXCESSO DE VELOCIDADE.\nO MESMO FOI ORIENTADO E ENTRAMOS EM CONTATO COM A EMPRESA PARA DEVOLUTIVA DA RECLAMAÇÃO.", resolucao:"Motorista orientado, contato com empresa realizado.", motorista_nome:"EVERTON RODRIGUES MESSIAS", veiculo_escalado:"CUB1I69 / 1087", origem_reclamacao:"E-mail"},
    {data:"2026-07-02", cliente_id:"cli-003", tipo:"Atraso",                status:"Em Andamento", descricao:"Veículo atrasou 25 minutos em relação ao horário programado.",                                                   resolucao:"",                                                                            motorista_nome:"CARLOS EDUARDO PEREIRA",  veiculo_escalado:"ABC1D23 / 1100", origem_reclamacao:"WhatsApp"},
    {data:"2026-07-08", cliente_id:"cli-005", tipo:"Veículo",               status:"Aberta",      descricao:"Ar-condicionado do veículo não está gelando adequadamente.",                                                     resolucao:"",                                                                            motorista_nome:"MARCOS ANTÔNIO OLIVEIRA",veiculo_escalado:"DMR7G00 / 1597", origem_reclamacao:"Telefone"},
    {data:"2026-07-15", cliente_id:"cli-011", tipo:"Limpeza",               status:"Resolvida",   descricao:"Veículo chegou ao cliente com interior sujo.",                                                                     resolucao:"Equipe de limpeza revisada, novo procedimento implementado.",                            motorista_nome:"JOSÉ ROBERTO DA SILVA",   veiculo_escalado:"",              origem_reclamacao:"E-mail"}
  ],
  prospeccoes: [
    {empresa:"GARDNER DENVER",           mes_ano:"07/2026", contato_nome:"ALEJANDRO DELGADO", contato_telefone:"11 2109-8900", contato_email:"alejandro.delgado@irco.com",         cidade:"JUNDIAI",   segmento:"Líder em fornecimento global de compressores",                       origem:"Site",       responsavel:"ANA PAULA MAYA",  status:"Em Contato",      data:"2026-07-05"},
    {empresa:"ELEVA TRAVESSEIROS",       mes_ano:"06/2026", contato_nome:"SCARLETE",          contato_telefone:"",             contato_email:"",                                   cidade:"",          segmento:"Indústria de travesseiros",                                            origem:"Indicação",  responsavel:"ANA PAULA MAYA",  status:"Proposta Enviada",data:"2026-06-12"},
    {empresa:"AGROEXPORT",               mes_ano:"07/2026", contato_nome:"RICARDO SANTOS",    contato_telefone:"11 5566-7788", contato_email:"ricardo@agroexport.com.br",          cidade:"SÃO PAULO", segmento:"Exportação agrícola",                                                origem:"LinkedIn",   responsavel:"RODRIGO FERREIRA",status:"Nova",             data:"2026-07-08"},
    {empresa:"VOTORANTIM CIMENTOS",      mes_ano:"07/2026", contato_nome:"MARIA APARECIDA",   contato_telefone:"11 3344-5566", contato_email:"maria@votorantim.com",              cidade:"SÃO PAULO", segmento:"Cimento e materiais de construção",                                  origem:"Visita",     responsavel:"ANA PAULA MAYA",  status:"Reunião Agendada", data:"2026-07-10"},
    {empresa:"AMBEV",                    mes_ano:"06/2026", contato_nome:"PAULO RICARDO",     contato_telefone:"11 2122-3344", contato_email:"paulo@ambev.com.br",                cidade:"JUNDIAI",   segmento:"Bebidas",                                                            origem:"Indicação",  responsavel:"RODRIGO FERREIRA",status:"Proposta Enviada",data:"2026-06-20"},
    {empresa:"NESTLÉ BRASIL",            mes_ano:"07/2026", contato_nome:"FERNANDA COSTA",    contato_telefone:"11 99887-7766", contato_email:"fernanda@nestle.com.br",           cidade:"CAJAMAR",   segmento:"Alimentos",                                                          origem:"Site",       responsavel:"ANA PAULA MAYA",  status:"Nova",             data:"2026-07-12"},
    {empresa:"PROCTER & GAMBLE",         mes_ano:"06/2026", contato_nome:"JOÃO MENDES",       contato_telefone:"11 4477-8899", contato_email:"joao.mendes@pg.com",               cidade:"SÃO PAULO", segmento:"Higiene e limpeza",                                                   origem:"LinkedIn",   responsavel:"RODRIGO FERREIRA",status:"Convertida",       data:"2026-06-15"},
    {empresa:"3M DO BRASIL",             mes_ano:"07/2026", contato_nome:"ALINE FERREIRA",    contato_telefone:"11 5566-1122", contato_email:"aline@3m.com",                     cidade:"SUMARÉ",    segmento:"Diversificada industrial",                                          origem:"Indicação",  responsavel:"ANA PAULA MAYA",  status:"Em Contato",       data:"2026-07-15"}
  ],
  propostas: [
    {numero_proposta:"001/2026", mes_ano:"06/2026", cliente_id:"cli-008", empresa:"ELEVA TRAVESSEIROS", contato_nome:"SCARLETE",       tipo_servico:"Fretamento Corporativo", responsavel:"ANA PAULA MAYA",  valor_proposto:"18500", km_mensal:"1800",  qtd_veiculos:"1", status:"Aprovada",       data_envio:"2026-06-12", data_validade:"2026-07-12"},
    {numero_proposta:"002/2026", mes_ano:"06/2026", cliente_id:"cli-009", empresa:"AMBEV",             contato_nome:"PAULO RICARDO",   tipo_servico:"Fretamento Corporativo", responsavel:"RODRIGO FERREIRA",valor_proposto:"67300", km_mensal:"7100",  qtd_veiculos:"4", status:"Em Negociação",  data_envio:"2026-06-20", data_validade:"2026-07-20"},
    {numero_proposta:"003/2026", mes_ano:"07/2026", cliente_id:"",        empresa:"PROCTER & GAMBLE",  contato_nome:"JOÃO MENDES",      tipo_servico:"Fretamento Corporativo", responsavel:"RODRIGO FERREIRA",valor_proposto:"41200", km_mensal:"4200",  qtd_veiculos:"2", status:"Aprovada",       data_envio:"2026-06-30", data_validade:"2026-07-30"},
    {numero_proposta:"004/2026", mes_ano:"07/2026", cliente_id:"",        empresa:"GARDNER DENVER",    contato_nome:"ALEJANDRO DELGADO",tipo_servico:"Fretamento Corporativo", responsavel:"ANA PAULA MAYA",  valor_proposto:"23800", km_mensal:"2400",  qtd_veiculos:"1", status:"Em Elaboração",  data_envio:"",            data_validade:""},
    {numero_proposta:"005/2026", mes_ano:"07/2026", cliente_id:"cli-010", empresa:"VOTORANTIM",        contato_nome:"MARIA APARECIDA",  tipo_servico:"Fretamento Corporativo", responsavel:"ANA PAULA MAYA",  valor_proposto:"98700", km_mensal:"10200", qtd_veiculos:"5", status:"Em Negociação",  data_envio:"2026-07-10", data_validade:"2026-08-10"},
    {numero_proposta:"006/2026", mes_ano:"07/2026", cliente_id:"",        empresa:"NESTLÉ BRASIL",     contato_nome:"FERNANDA COSTA",   tipo_servico:"Fretamento Corporativo", responsavel:"RODRIGO FERREIRA",valor_proposto:"52000", km_mensal:"5500",  qtd_veiculos:"3", status:"Em Elaboração",  data_envio:"",            data_validade:""}
  ]
};
